### ISSUE TITLE
Meet Segmentation fault (core dumped) while training

### ISSUE THREAD

**Issue by liuxy416** [oandrienko/fast-semantic-segmentation#16]
I was training both PSPNet and ICNet using the method provided from README, But Segmentation fault (core dumped) occured on both Net while training and no other logs. Could anybody please tell me how to train the network?

**Comment by smohan10** [comment]
I get the same error. Segmentation fault after a few epochs on an AWS g3 8 XL instance.

**Comment by oandrienko** [comment]
Hey @liuxy416, @smohan10, thanks for posting this issue and sorry for the delayed reply. 

I think this will most likely be a Tensorflow issue since I have never run into this problem with the current codebase. I have however, run into seg faults before when using Tensorflow. Your best bet might be to update your tensorflow and CUDA versions on your machines. 

I will close the issue for now but if you figure that the problem might be something specific to the project please reopen the issue. Sorry I couldn't be more help.
