### ISSUE TITLE
Training logs and multi-gpu

### ISSUE THREAD

**Issue by mattpfr** [oandrienko/fast-semantic-segmentation#4]
Hi! I am looking at your code, and wanted to train ICNet as you describe it in you nice documentation. I have two questions regarding the PSPNet fine tuning part where you use the `train_mem_saving.py`
- I was expecting to have some feedback along the way when its training, but besides 2 times a log that a checkpoint was saved, nothing is printed, is it normal ?
- I also tried to use it with two gpus. I tried to change the `num_clones` flag but I get an `KeyError` that comes from the `create_clones()` in the `trainer.py`. Is there anything else I should do to use several GPUs to train ?

Thanks a lot :)

**Comment by mattpfr** [comment]
Hi! Thanks a lot for the fix :) It definitely helps!  For the logs, I was refering to the command line logs, but I agree there is all the information in tensorboard! 

Thanks again!

**Comment by mattpfr** [comment]
@oandrienko Hi, another related thing. I have been trying now to use train_mem_saving.py on a machine with several gpus, but it seems like the training is not faster. I am currently running the script on a machine with one gpu, and it takes around 4 secs per step. I run it on another machine with 3 gpus, set the num_clones to 3, but the steps are also taking around 4 secs, although all the gpus are working. I would have expected to have faster step ? Or each gpu is taking 4 secs, and their results are fused ?

You mentioned in another ticket that it took more than one week to train on a single gpu but that you brought it down to 2 or 3 days on multiple gpus. What was your setup ?

**Comment by oandrienko** [comment]
@mattpfr Hey, sorry again for the delayed reply! Was super busy and had to look into this more. For the previous issue you mentioned, I had setup a multi-GPU setup using the`train.py` script so was not aware of the issue. 

However, I did end up replicating the issue you had with the 'train_mem_saving.py` script. When probing the memory of each GPU, I also noticed that `gpu:0` would also always use more memory than the other GPUs. It turns out that the [gradient checkpointing](https://github.com/openai/gradient-checkpointing) module had a problem where specific operations had their device field cleared (causing a bunch of ops to be pinned to `gpu:0` instead of the other available GPUs). The pull request fixing this in the original project can be found at: https://github.com/openai/gradient-checkpointing/pull/34.

I have updated the equivalent file in this project at `third_party/memory_saving_gradients.py` as of commit `100d966`. I also verified the `train_mem_saving.py` script and saw a somewhat linear speedup as you originally expected.

Hope this helps!

**Comment by mattpfr** [comment]
@oandrienko  Thanks for the answer! I was looking on my side as well and noticed the issue with the memory. To be honest, I am still struggling with the multi gpu training, especially on the memory side. If I run it on a single Titan X, everything is fine with your parameters (batch size 8, training res 1025x1025), but when I use 3 gpus , with the same parameters, I very quickly get some cuda out of memory, and ExhaustedResources exceptions, so I had to set the resolution to half the original size (512x1024). That works, but I noticed that the loss is decreasing slower than with the single gpu with higher training resolution. Also, the speedup is not really 3x, for 3 gpus, but something like 2 or 2.5 at most.

Did you experience the same issues with memory ? Do you manage to training multi gpu with 1025x1025 input size ?

**Comment by oandrienko** [comment]
After the fix I mentioned, you shouldn't have anymore memory issues running on a Titan X (which has about 12 GB of memory)! If you used more than one clone prior to commit `100d966`, then the memory issue is expected due to the bug referenced above. With the updated gradient checkpointing module, there should be almost no memory difference between running one a single or multiple GPUs as the same model is copied to each device. For PSPNet50, I was able to train on 1025x1025 sized image crops with a batch size of 8 on a single 1080 Ti. If I remember correctly, I believe the memory usage approached about 10GB. Did you make sure to sync to the most recent commit?

In terms of speed, you should expect a near linear speedup with 3 GPUs. It won't be exactly linear though. To make sure it's as close as possible, double check that you have the correct batch queue capacity, batch queue threads count and prefetch queue capacity set in your configs. These will depend on your setup. The input pipeline can slow down training if the capacity is too low or too large for example. 

If you need, feel free to send me and email and I will try my best to help.

**Comment by oandrienko** [comment]
@mattpfr ^ Notifying you that I made some corrections on the comment above.
