### ISSUE TITLE
hi, can you give a "readme" about how to train our dataset from scratch?

### ISSUE THREAD

**Issue by zhangyunming** [oandrienko/fast-semantic-segmentation#5]

**Comment by zhangyunming** [comment]
hi. thank you for share the code , i think maybe you can give a Short tutorial about hor to train our dataset from scratch, because somebody woul use the code to train therr own data,and  modify the basenet.
thanks

**Comment by oandrienko** [comment]
When you refer to training from scratch, do you meaning without Transfer Learning? This will probably be unfeasible since the network would most likely not converge. If you mean training from a backbone like ResNet50, you need to ideally first train PSPNet50 initialized with ResNet50 weights. OR, you can train ICNet directly from ResNet50 weights but this will lead to lower accuracies.

If you want to train using your own dataset, follow the guide [here](https://github.com/oandrienko/fast-semantic-segmentation/blob/master/docs/icnet.md). The general procedure is summarized as:
1. Create your own TFRecord creator script as outlined [here](https://github.com/oandrienko/fast-semantic-segmentation/blob/master/docs/datasets.md). Then generate your train and eval records.
2. *Stage 0 Pretraining*: Train PSPNet50 from ResNet50 weights
3. *Stage 1 Training*: Initialize ICNet (without compression with all kernels) from the PSPNet50 weights and train
4. Apply compression to the resulting high accuracy ICNet model
5. *Stage 2 Training*: Retrain the compressed ICNet model to regain accuracy.

**Comment by oandrienko** [comment]
Hope this helps. I’m going to close the issue for now. If you provide some more, detail re-open the issue and I can try to help.
