### ISSUE TITLE
ICNet stage 1 checkpoint

### ISSUE THREAD

**Issue by cbbjames** [oandrienko/fast-semantic-segmentation#6]
Great work!
A small question, could you also provide the Stage 1 ICNet in Model Zoo?
Did you manage to reproduce the performance of ICNet in their paper?
Thanks!

**Comment by oandrienko** [comment]
Hey @cbbjames, thanks for your interest. I got some emails asking me for the stage 1 checkpoint too, so I've just added it to the model zoo page. 

In terms of performance for the models I trained back in August: the stage 1 (uncompressed) model achieves  `~70%` mIoU compared to the stage 2 (compressed) model which gets ~`66%`mIoU. This is on the Cityscapes Validation set. The compressed model is about `1.7%`mIoU off from the original ICNet paper, which I believe is caused by the fact that I retrain only once during compression.
